const { PrismaClient } = require('@prisma/client');
const fs = require('fs');
const path = require('path');

const prisma = new PrismaClient();

// Excel data from JSON export
const excelData = [
    { imalatNo: 250908, musteri: "EFATUR 1", aracGeldiMi: true, aracMarka: "FORD", model: "3545 D", tip: "HAVUZ DAMPER", malzemeCinsi: "HARDOX", m3: 16, plazmaProgrami: true, sacMalzemeKontrolu: true, plazmaKesim: true, damperSasiPlazmaKesim: true, presBukum: true, aracBraket: true, damperSasi: true, sasiYukleme: true, milAltKutuk: true, taban: true, yan: true, onGogus: true, arkaKapak: true, yuklemeMalzemesi: true, damperKurulmasi: true, damperKaynak: true, sasiKapakSiperlik: true, yukleme: true, hidrolik: true, boyaHazirlik: true, boya: true, elektrik: true, hava: true, tamamlama: true, sonKontrol: true, kurumMuayenesi: "YOK", dmoMuayenesi: "YOK", teslimat: true },
    { imalatNo: 250909, musteri: "EFATUR 2", aracGeldiMi: true, aracMarka: "FORD", model: "3545 D", tip: "HAVUZ DAMPER", malzemeCinsi: "HARDOX", m3: 16, plazmaProgrami: true, sacMalzemeKontrolu: true, plazmaKesim: true, damperSasiPlazmaKesim: true, presBukum: true, aracBraket: true, damperSasi: true, sasiYukleme: true, milAltKutuk: true, taban: true, yan: true, onGogus: true, arkaKapak: true, yuklemeMalzemesi: true, damperKurulmasi: true, damperKaynak: true, sasiKapakSiperlik: true, yukleme: true, hidrolik: true, boyaHazirlik: true, boya: true, elektrik: true, hava: true, tamamlama: true, sonKontrol: true, kurumMuayenesi: "YOK", dmoMuayenesi: "YOK", teslimat: true },
    { imalatNo: 250910, musteri: "EFATUR 3", aracGeldiMi: true, aracMarka: "FORD", model: "3545 D", tip: "HAVUZ DAMPER", malzemeCinsi: "HARDOX", m3: 16, plazmaProgrami: true, sacMalzemeKontrolu: true, plazmaKesim: true, damperSasiPlazmaKesim: true, presBukum: true, aracBraket: true, damperSasi: true, sasiYukleme: true, milAltKutuk: true, taban: true, yan: true, onGogus: true, arkaKapak: true, yuklemeMalzemesi: true, damperKurulmasi: true, damperKaynak: true, sasiKapakSiperlik: true, yukleme: true, hidrolik: true, boyaHazirlik: true, boya: true, elektrik: true, hava: true, tamamlama: true, sonKontrol: true, kurumMuayenesi: "YOK", dmoMuayenesi: "YOK", teslimat: true },
    { imalatNo: 250911, musteri: "EFATUR 4", aracGeldiMi: true, aracMarka: "FORD", model: "3545 D", tip: "HAVUZ DAMPER", malzemeCinsi: "HARDOX", m3: 16, plazmaProgrami: true, sacMalzemeKontrolu: true, plazmaKesim: true, damperSasiPlazmaKesim: true, presBukum: true, aracBraket: true, damperSasi: true, sasiYukleme: true, milAltKutuk: true, taban: true, yan: true, onGogus: true, arkaKapak: true, yuklemeMalzemesi: true, damperKurulmasi: true, damperKaynak: true, sasiKapakSiperlik: true, yukleme: true, hidrolik: true, boyaHazirlik: true, boya: true, elektrik: true, hava: true, tamamlama: true, sonKontrol: true, kurumMuayenesi: "YOK", dmoMuayenesi: "YOK", teslimat: true },
    { imalatNo: 250912, musteri: "EFATUR 5", aracGeldiMi: true, aracMarka: "FORD", model: "3545 D", tip: "HAVUZ DAMPER", malzemeCinsi: "HARDOX", m3: 16, plazmaProgrami: true, sacMalzemeKontrolu: true, plazmaKesim: true, damperSasiPlazmaKesim: true, presBukum: true, aracBraket: true, damperSasi: true, sasiYukleme: true, milAltKutuk: true, taban: true, yan: true, onGogus: true, arkaKapak: true, yuklemeMalzemesi: true, damperKurulmasi: true, damperKaynak: true, sasiKapakSiperlik: true, yukleme: true, hidrolik: true, boyaHazirlik: true, boya: true, elektrik: true, hava: true, tamamlama: true, sonKontrol: true, kurumMuayenesi: "YOK", dmoMuayenesi: "YOK", teslimat: true },
    { imalatNo: 250913, musteri: "EFATUR 6", aracGeldiMi: true, aracMarka: "FORD", model: "3545 D", tip: "HAVUZ DAMPER", malzemeCinsi: "HARDOX", m3: 16, plazmaProgrami: true, sacMalzemeKontrolu: true, plazmaKesim: true, damperSasiPlazmaKesim: true, presBukum: true, aracBraket: true, damperSasi: true, sasiYukleme: true, milAltKutuk: true, taban: true, yan: true, onGogus: true, arkaKapak: true, yuklemeMalzemesi: true, damperKurulmasi: true, damperKaynak: true, sasiKapakSiperlik: true, yukleme: true, hidrolik: true, boyaHazirlik: true, boya: true, elektrik: true, hava: true, tamamlama: true, sonKontrol: true, kurumMuayenesi: "YOK", dmoMuayenesi: "YOK", teslimat: true },
    { imalatNo: 250914, musteri: "EFATUR 7", aracGeldiMi: true, aracMarka: "FORD", model: "3545 D", tip: "HAVUZ DAMPER", malzemeCinsi: "HARDOX", m3: 16, plazmaProgrami: true, sacMalzemeKontrolu: true, plazmaKesim: true, damperSasiPlazmaKesim: true, presBukum: true, aracBraket: true, damperSasi: true, sasiYukleme: true, milAltKutuk: true, taban: true, yan: true, onGogus: true, arkaKapak: true, yuklemeMalzemesi: true, damperKurulmasi: true, damperKaynak: true, sasiKapakSiperlik: true, yukleme: true, hidrolik: true, boyaHazirlik: true, boya: true, elektrik: true, hava: true, tamamlama: true, sonKontrol: true, kurumMuayenesi: "YOK", dmoMuayenesi: "YOK", teslimat: true },
    { imalatNo: 250915, musteri: "EFATUR 8", aracGeldiMi: true, aracMarka: "FORD", model: "3545 D", tip: "HAVUZ DAMPER", malzemeCinsi: "HARDOX", m3: 16, plazmaProgrami: true, sacMalzemeKontrolu: true, plazmaKesim: true, damperSasiPlazmaKesim: true, presBukum: true, aracBraket: true, damperSasi: true, sasiYukleme: true, milAltKutuk: true, taban: true, yan: true, onGogus: true, arkaKapak: true, yuklemeMalzemesi: true, damperKurulmasi: true, damperKaynak: true, sasiKapakSiperlik: true, yukleme: true, hidrolik: true, boyaHazirlik: true, boya: true, elektrik: true, hava: true, tamamlama: true, sonKontrol: true, kurumMuayenesi: "YOK", dmoMuayenesi: "YOK", teslimat: true },
    { imalatNo: 250916, musteri: "EFATUR 9", aracGeldiMi: true, aracMarka: "FORD", model: "3545 D", tip: "HAVUZ DAMPER", malzemeCinsi: "HARDOX", m3: 16, plazmaProgrami: true, sacMalzemeKontrolu: true, plazmaKesim: true, damperSasiPlazmaKesim: true, presBukum: true, aracBraket: true, damperSasi: true, sasiYukleme: true, milAltKutuk: true, taban: true, yan: true, onGogus: true, arkaKapak: true, yuklemeMalzemesi: true, damperKurulmasi: true, damperKaynak: true, sasiKapakSiperlik: true, yukleme: true, hidrolik: true, boyaHazirlik: true, boya: true, elektrik: true, hava: true, tamamlama: true, sonKontrol: true, kurumMuayenesi: "YOK", dmoMuayenesi: "YOK", teslimat: true },
    { imalatNo: 250917, musteri: "EFATUR 10", aracGeldiMi: true, aracMarka: "FORD", model: "3545 D", tip: "HAVUZ DAMPER", malzemeCinsi: "HARDOX", m3: 16, plazmaProgrami: true, sacMalzemeKontrolu: true, plazmaKesim: true, damperSasiPlazmaKesim: true, presBukum: true, aracBraket: true, damperSasi: true, sasiYukleme: true, milAltKutuk: true, taban: true, yan: true, onGogus: true, arkaKapak: true, yuklemeMalzemesi: true, damperKurulmasi: true, damperKaynak: true, sasiKapakSiperlik: true, yukleme: true, hidrolik: true, boyaHazirlik: true, boya: true, elektrik: true, hava: true, tamamlama: true, sonKontrol: true, kurumMuayenesi: "YOK", dmoMuayenesi: "YOK", teslimat: true },
    { imalatNo: 250918, musteri: "EFATUR 11", aracGeldiMi: true, aracMarka: "FORD", model: "3545 D", tip: "HAVUZ DAMPER", malzemeCinsi: "HARDOX", m3: 16, plazmaProgrami: true, sacMalzemeKontrolu: true, plazmaKesim: true, damperSasiPlazmaKesim: true, presBukum: true, aracBraket: true, damperSasi: true, sasiYukleme: true, milAltKutuk: true, taban: true, yan: true, onGogus: true, arkaKapak: true, yuklemeMalzemesi: true, damperKurulmasi: true, damperKaynak: true, sasiKapakSiperlik: true, yukleme: true, hidrolik: true, boyaHazirlik: true, boya: true, elektrik: true, hava: true, tamamlama: true, sonKontrol: true, kurumMuayenesi: "YOK", dmoMuayenesi: "YOK", teslimat: true },
    { imalatNo: 250919, musteri: "EFATUR 12", aracGeldiMi: true, aracMarka: "FORD", model: "3545 D", tip: "HAVUZ DAMPER", malzemeCinsi: "HARDOX", m3: 16, plazmaProgrami: true, sacMalzemeKontrolu: true, plazmaKesim: true, damperSasiPlazmaKesim: true, presBukum: true, aracBraket: true, damperSasi: true, sasiYukleme: true, milAltKutuk: true, taban: true, yan: true, onGogus: true, arkaKapak: true, yuklemeMalzemesi: true, damperKurulmasi: true, damperKaynak: true, sasiKapakSiperlik: true, yukleme: true, hidrolik: true, boyaHazirlik: true, boya: true, elektrik: true, hava: true, tamamlama: true, sonKontrol: true, kurumMuayenesi: "YOK", dmoMuayenesi: "YOK", teslimat: true },
    { imalatNo: 250774, musteri: "TRABZON YOMRA BLD", aracGeldiMi: true, aracMarka: "MERCEDES", model: "3345 K", tip: "HAVUZ DAMPER", malzemeCinsi: "HARDOX", m3: 14, plazmaProgrami: true, sacMalzemeKontrolu: true, plazmaKesim: true, damperSasiPlazmaKesim: true, presBukum: true, aracBraket: true, damperSasi: true, sasiYukleme: true, milAltKutuk: true, taban: true, yan: true, onGogus: true, arkaKapak: true, yuklemeMalzemesi: true, damperKurulmasi: true, damperKaynak: true, sasiKapakSiperlik: true, yukleme: true, hidrolik: false, boyaHazirlik: false, boya: false, elektrik: false, hava: false, tamamlama: false, sonKontrol: false, kurumMuayenesi: "YOK", dmoMuayenesi: "MUAYENE YOK", teslimat: false },
    { imalatNo: 250778, musteri: "BOLU İÖİ", aracGeldiMi: true, aracMarka: "MERCEDES", model: "3345 K", tip: "HAVUZ DAMPER + HİDROLİK KAPAK", malzemeCinsi: "HARDOX", m3: 14, plazmaProgrami: true, sacMalzemeKontrolu: true, plazmaKesim: true, damperSasiPlazmaKesim: true, presBukum: true, aracBraket: true, damperSasi: true, sasiYukleme: true, milAltKutuk: true, taban: true, yan: true, onGogus: true, arkaKapak: true, yuklemeMalzemesi: true, damperKurulmasi: true, damperKaynak: true, sasiKapakSiperlik: false, yukleme: false, hidrolik: false, boyaHazirlik: false, boya: false, elektrik: false, hava: false, tamamlama: false, sonKontrol: false, kurumMuayenesi: "YOK", dmoMuayenesi: "MUAYENE YOK", teslimat: false },
    { imalatNo: 250015, musteri: "ESKİŞEHİR ODUNPAZARI BLD 1", aracGeldiMi: true, aracMarka: "FORD", model: "1833", tip: "HAVUZ DAMPER", malzemeCinsi: "HARDOX", m3: 8, plazmaProgrami: true, sacMalzemeKontrolu: true, plazmaKesim: true, damperSasiPlazmaKesim: true, presBukum: true, aracBraket: false, damperSasi: true, sasiYukleme: false, milAltKutuk: true, taban: true, yan: true, onGogus: true, arkaKapak: true, yuklemeMalzemesi: true, damperKurulmasi: true, damperKaynak: false, sasiKapakSiperlik: false, yukleme: false, hidrolik: false, boyaHazirlik: false, boya: false, elektrik: false, hava: false, tamamlama: false, sonKontrol: false, kurumMuayenesi: "YOK", dmoMuayenesi: "MUAYENE YOK", teslimat: false },
    { imalatNo: 250016, musteri: "ESKİŞEHİR ODUNPAZARI BLD 2", aracGeldiMi: true, aracMarka: "FORD", model: "1833", tip: "HAVUZ DAMPER", malzemeCinsi: "HARDOX", m3: 8, plazmaProgrami: true, sacMalzemeKontrolu: true, plazmaKesim: true, damperSasiPlazmaKesim: true, presBukum: true, aracBraket: false, damperSasi: true, sasiYukleme: false, milAltKutuk: true, taban: true, yan: true, onGogus: true, arkaKapak: true, yuklemeMalzemesi: true, damperKurulmasi: true, damperKaynak: false, sasiKapakSiperlik: false, yukleme: false, hidrolik: false, boyaHazirlik: false, boya: false, elektrik: false, hava: false, tamamlama: false, sonKontrol: false, kurumMuayenesi: "YOK", dmoMuayenesi: "MUAYENE YOK", teslimat: false },
    { imalatNo: 250775, musteri: "AFYON İÖİ 1", aracGeldiMi: true, aracMarka: "MERCEDES", model: "3345 K", tip: "HAVUZ DAMPER", malzemeCinsi: "HARDOX", m3: 14, plazmaProgrami: true, sacMalzemeKontrolu: true, plazmaKesim: true, damperSasiPlazmaKesim: true, presBukum: true, aracBraket: true, damperSasi: true, sasiYukleme: true, milAltKutuk: true, taban: true, yan: true, onGogus: true, arkaKapak: true, yuklemeMalzemesi: true, damperKurulmasi: true, damperKaynak: true, sasiKapakSiperlik: true, yukleme: true, hidrolik: true, boyaHazirlik: false, boya: false, elektrik: false, hava: false, tamamlama: false, sonKontrol: false, kurumMuayenesi: "YOK", dmoMuayenesi: "MUAYENE YOK", teslimat: false },
    { imalatNo: 250776, musteri: "AFYON İÖİ 2", aracGeldiMi: true, aracMarka: "MERCEDES", model: "3345 K", tip: "HAVUZ DAMPER", malzemeCinsi: "HARDOX", m3: 14, plazmaProgrami: true, sacMalzemeKontrolu: true, plazmaKesim: true, damperSasiPlazmaKesim: true, presBukum: true, aracBraket: true, damperSasi: true, sasiYukleme: true, milAltKutuk: true, taban: true, yan: true, onGogus: true, arkaKapak: true, yuklemeMalzemesi: true, damperKurulmasi: true, damperKaynak: true, sasiKapakSiperlik: true, yukleme: true, hidrolik: false, boyaHazirlik: false, boya: false, elektrik: false, hava: false, tamamlama: false, sonKontrol: false, kurumMuayenesi: "YOK", dmoMuayenesi: "MUAYENE YOK", teslimat: false },
    { imalatNo: 250777, musteri: "AFYON İÖİ 3", aracGeldiMi: true, aracMarka: "MERCEDES", model: "3345 K", tip: "HAVUZ DAMPER", malzemeCinsi: "HARDOX", m3: 14, plazmaProgrami: true, sacMalzemeKontrolu: true, plazmaKesim: true, damperSasiPlazmaKesim: true, presBukum: true, aracBraket: true, damperSasi: true, sasiYukleme: true, milAltKutuk: true, taban: true, yan: true, onGogus: true, arkaKapak: true, yuklemeMalzemesi: true, damperKurulmasi: true, damperKaynak: true, sasiKapakSiperlik: true, yukleme: true, hidrolik: false, boyaHazirlik: false, boya: false, elektrik: false, hava: false, tamamlama: false, sonKontrol: false, kurumMuayenesi: "YOK", dmoMuayenesi: "MUAYENE YOK", teslimat: false },
    { imalatNo: 250779, musteri: "BOLU İÖİ 2", aracGeldiMi: true, aracMarka: "MERCEDES", model: "3345 K", tip: "HAVUZ DAMPER + HİDROLİK KAPAK", malzemeCinsi: "HARDOX", m3: 14, plazmaProgrami: true, sacMalzemeKontrolu: true, plazmaKesim: true, damperSasiPlazmaKesim: true, presBukum: true, aracBraket: true, damperSasi: true, sasiYukleme: true, milAltKutuk: true, taban: true, yan: true, onGogus: true, arkaKapak: true, yuklemeMalzemesi: true, damperKurulmasi: false, damperKaynak: false, sasiKapakSiperlik: false, yukleme: false, hidrolik: false, boyaHazirlik: false, boya: false, elektrik: false, hava: false, tamamlama: false, sonKontrol: false, kurumMuayenesi: "YOK", dmoMuayenesi: "MUAYENE YOK", teslimat: false },
    { imalatNo: 250781, musteri: "KÜTAHYA BLD 1", aracGeldiMi: true, aracMarka: "MAN", model: "2533 D", tip: "KÖŞELİ DAMPER", malzemeCinsi: "ST52", m3: 12, plazmaProgrami: true, sacMalzemeKontrolu: true, plazmaKesim: true, damperSasiPlazmaKesim: true, presBukum: true, aracBraket: true, damperSasi: true, sasiYukleme: true, milAltKutuk: true, taban: true, yan: true, onGogus: true, arkaKapak: true, yuklemeMalzemesi: true, damperKurulmasi: false, damperKaynak: false, sasiKapakSiperlik: false, yukleme: false, hidrolik: false, boyaHazirlik: false, boya: false, elektrik: false, hava: false, tamamlama: false, sonKontrol: false, kurumMuayenesi: "YOK", dmoMuayenesi: "MUAYENE YOK", teslimat: false },
    { imalatNo: 250782, musteri: "KÜTAHYA BLD 2", aracGeldiMi: true, aracMarka: "MAN", model: "2533 D", tip: "KÖŞELİ DAMPER", malzemeCinsi: "ST52", m3: 12, plazmaProgrami: true, sacMalzemeKontrolu: true, plazmaKesim: true, damperSasiPlazmaKesim: true, presBukum: true, aracBraket: true, damperSasi: true, sasiYukleme: true, milAltKutuk: true, taban: true, yan: true, onGogus: true, arkaKapak: true, yuklemeMalzemesi: true, damperKurulmasi: false, damperKaynak: false, sasiKapakSiperlik: false, yukleme: false, hidrolik: false, boyaHazirlik: false, boya: false, elektrik: false, hava: false, tamamlama: false, sonKontrol: false, kurumMuayenesi: "YOK", dmoMuayenesi: "MUAYENE YOK", teslimat: false },
    { imalatNo: 250783, musteri: "SAMSUN BLD", aracGeldiMi: false, aracMarka: "MERCEDES", model: "4145 D", tip: "HAVUZ DAMPER", malzemeCinsi: "HARDOX", m3: 18, plazmaProgrami: true, sacMalzemeKontrolu: true, plazmaKesim: true, damperSasiPlazmaKesim: true, presBukum: true, aracBraket: false, damperSasi: false, sasiYukleme: false, milAltKutuk: true, taban: true, yan: true, onGogus: true, arkaKapak: true, yuklemeMalzemesi: true, damperKurulmasi: false, damperKaynak: false, sasiKapakSiperlik: false, yukleme: false, hidrolik: false, boyaHazirlik: false, boya: false, elektrik: false, hava: false, tamamlama: false, sonKontrol: false, kurumMuayenesi: "YOK", dmoMuayenesi: "MUAYENE YOK", teslimat: false },
    { imalatNo: 250784, musteri: "HATAY BLD 1", aracGeldiMi: false, aracMarka: "MERCEDES", model: "4145 D", tip: "HAVUZ DAMPER", malzemeCinsi: "HARDOX", m3: 18, plazmaProgrami: true, sacMalzemeKontrolu: true, plazmaKesim: true, damperSasiPlazmaKesim: true, presBukum: true, aracBraket: false, damperSasi: false, sasiYukleme: false, milAltKutuk: true, taban: true, yan: true, onGogus: true, arkaKapak: true, yuklemeMalzemesi: true, damperKurulmasi: false, damperKaynak: false, sasiKapakSiperlik: false, yukleme: false, hidrolik: false, boyaHazirlik: false, boya: false, elektrik: false, hava: false, tamamlama: false, sonKontrol: false, kurumMuayenesi: "YOK", dmoMuayenesi: "MUAYENE YOK", teslimat: false },
    { imalatNo: 250785, musteri: "HATAY BLD 2", aracGeldiMi: false, aracMarka: "MERCEDES", model: "4145 D", tip: "HAVUZ DAMPER", malzemeCinsi: "HARDOX", m3: 18, plazmaProgrami: true, sacMalzemeKontrolu: true, plazmaKesim: true, damperSasiPlazmaKesim: true, presBukum: true, aracBraket: false, damperSasi: false, sasiYukleme: false, milAltKutuk: true, taban: true, yan: true, onGogus: true, arkaKapak: true, yuklemeMalzemesi: true, damperKurulmasi: false, damperKaynak: false, sasiKapakSiperlik: false, yukleme: false, hidrolik: false, boyaHazirlik: false, boya: false, elektrik: false, hava: false, tamamlama: false, sonKontrol: false, kurumMuayenesi: "YOK", dmoMuayenesi: "MUAYENE YOK", teslimat: false },
    { imalatNo: 250786, musteri: "ANKARA MAMAK BLD", aracGeldiMi: true, aracMarka: "FORD", model: "3545 D", tip: "HAVUZ DAMPER", malzemeCinsi: "HARDOX", m3: 16, plazmaProgrami: true, sacMalzemeKontrolu: true, plazmaKesim: true, damperSasiPlazmaKesim: true, presBukum: true, aracBraket: false, damperSasi: false, sasiYukleme: false, milAltKutuk: true, taban: true, yan: true, onGogus: true, arkaKapak: true, yuklemeMalzemesi: true, damperKurulmasi: false, damperKaynak: false, sasiKapakSiperlik: false, yukleme: false, hidrolik: false, boyaHazirlik: false, boya: false, elektrik: false, hava: false, tamamlama: false, sonKontrol: false, kurumMuayenesi: "YOK", dmoMuayenesi: "MUAYENE YOK", teslimat: false },
    { imalatNo: 250787, musteri: "İZMİR KARABAĞLAR BLD", aracGeldiMi: false, aracMarka: "MERCEDES", model: "3345 K", tip: "HAVUZ DAMPER", malzemeCinsi: "HARDOX", m3: 14, plazmaProgrami: true, sacMalzemeKontrolu: true, plazmaKesim: true, damperSasiPlazmaKesim: false, presBukum: false, aracBraket: false, damperSasi: false, sasiYukleme: false, milAltKutuk: false, taban: false, yan: false, onGogus: false, arkaKapak: false, yuklemeMalzemesi: false, damperKurulmasi: false, damperKaynak: false, sasiKapakSiperlik: false, yukleme: false, hidrolik: false, boyaHazirlik: false, boya: false, elektrik: false, hava: false, tamamlama: false, sonKontrol: false, kurumMuayenesi: "YOK", dmoMuayenesi: "MUAYENE YOK", teslimat: false },
    { imalatNo: 250788, musteri: "BURSA NİLÜFER BLD", aracGeldiMi: false, aracMarka: "FORD", model: "3545 D", tip: "HAVUZ DAMPER", malzemeCinsi: "HARDOX", m3: 16, plazmaProgrami: true, sacMalzemeKontrolu: true, plazmaKesim: false, damperSasiPlazmaKesim: false, presBukum: false, aracBraket: false, damperSasi: false, sasiYukleme: false, milAltKutuk: false, taban: false, yan: false, onGogus: false, arkaKapak: false, yuklemeMalzemesi: false, damperKurulmasi: false, damperKaynak: false, sasiKapakSiperlik: false, yukleme: false, hidrolik: false, boyaHazirlik: false, boya: false, elektrik: false, hava: false, tamamlama: false, sonKontrol: false, kurumMuayenesi: "YOK", dmoMuayenesi: "MUAYENE YOK", teslimat: false },
    { imalatNo: 250789, musteri: "KONYA MERAM BLD", aracGeldiMi: false, aracMarka: "MERCEDES", model: "3345 K", tip: "HAVUZ DAMPER + HİDROLİK KAPAK", malzemeCinsi: "HARDOX", m3: 14, plazmaProgrami: true, sacMalzemeKontrolu: false, plazmaKesim: false, damperSasiPlazmaKesim: false, presBukum: false, aracBraket: false, damperSasi: false, sasiYukleme: false, milAltKutuk: false, taban: false, yan: false, onGogus: false, arkaKapak: false, yuklemeMalzemesi: false, damperKurulmasi: false, damperKaynak: false, sasiKapakSiperlik: false, yukleme: false, hidrolik: false, boyaHazirlik: false, boya: false, elektrik: false, hava: false, tamamlama: false, sonKontrol: false, kurumMuayenesi: "YOK", dmoMuayenesi: "MUAYENE YOK", teslimat: false },
    { imalatNo: 250790, musteri: "GAZİANTEP ŞAHİNBEY BLD", aracGeldiMi: false, aracMarka: "MAN", model: "41440", tip: "HAVUZ DAMPER", malzemeCinsi: "HARDOX", m3: 20, plazmaProgrami: false, sacMalzemeKontrolu: false, plazmaKesim: false, damperSasiPlazmaKesim: false, presBukum: false, aracBraket: false, damperSasi: false, sasiYukleme: false, milAltKutuk: false, taban: false, yan: false, onGogus: false, arkaKapak: false, yuklemeMalzemesi: false, damperKurulmasi: false, damperKaynak: false, sasiKapakSiperlik: false, yukleme: false, hidrolik: false, boyaHazirlik: false, boya: false, elektrik: false, hava: false, tamamlama: false, sonKontrol: false, kurumMuayenesi: "YOK", dmoMuayenesi: "MUAYENE YOK", teslimat: false },
];

async function main() {
    console.log('Starting to seed database...');

    // Clear existing data
    await prisma.damper.deleteMany({});
    console.log('Cleared existing data');

    // Insert new data
    for (const data of excelData) {
        await prisma.damper.create({ data });
    }

    console.log(`Seeded ${excelData.length} damper records`);
}

main()
    .catch((e) => {
        console.error(e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
