-- Add StepToggleEvent table (non-destructive)
-- Keeps a raw history of step/substep toggle changes for future analytics.

CREATE TABLE IF NOT EXISTS "StepToggleEvent" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" INTEGER,
  "username" TEXT,
  "productType" TEXT NOT NULL,
  "productId" INTEGER NOT NULL,
  "fieldKey" TEXT NOT NULL,
  "fromValue" BOOLEAN,
  "toValue" BOOLEAN,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS "StepToggleEvent_productType_productId_idx"
  ON "StepToggleEvent"("productType", "productId");

CREATE INDEX IF NOT EXISTS "StepToggleEvent_fieldKey_idx"
  ON "StepToggleEvent"("fieldKey");

CREATE INDEX IF NOT EXISTS "StepToggleEvent_createdAt_idx"
  ON "StepToggleEvent"("createdAt");

